### ISSUE TITLE
API use of the term 'Utils' is obstructing in-game use of base class with the same name 

### ISSUE THREAD

**Issue by mentuat** [BuongiornoMIP/GamifiveSDK#11]
API is using the general term 'Utils' at the root level which unfortunately is overriding my games (and possibly other developers?) use of the same term within the games and causing them to fail when calling game specific Utils functions :(

**Comment by ffognani** [comment]
Hi, the module was already renamed GamifiveSDKUtils (I'm going to update the docs right now).

Let me know if you can see the new version or if you have troubles.

Cheers,
Fabio

**Comment by mentuat** [comment]
aha great thanks!
