### ISSUE TITLE
Implementing Lite Mode + Lvl attribute

### ISSUE THREAD

**Issue by apands** [BuongiornoMIP/GamifiveSDK#12]
Hello,
I'm trying to implement API in Lite Mode with level feature into my game Island Blocks: http://appsworld.gamifive-app.com/html5gameplay/cfd39083c79f294fe7c616026638a8d1/game/island-blocks

There seems to be a problem with it freezing after 80% loading. If I set debug to true it works fine. 
![unnamed](https://cloud.githubusercontent.com/assets/7591312/11246812/69224d28-8e2a-11e5-82af-f28199f7d910.png)

Update:
The problems is solved (or mostly solved) - I've added a check whether the API was initiated before trying to load the level and it solved the freezing problem. Now the problem is level attribute: well reported in the leaderboard script but ‘top level reached’ is not retrieved when I change device. 
I'll look into it and report back later. Will close the issue if figure it out.

**Comment by ffognani** [comment]
Hi, could you please upload the non-minified version of main-html.js for debugging? It would be easier to see the code and try to figure out where the error is.

**Comment by apands** [comment]
Okay, I've solved the problem. Everything is fine now. Sorry for bothering.
