### ISSUE TITLE
Double scrolling bar

### ISSUE THREAD

**Issue by apands** [BuongiornoMIP/GamifiveSDK#13]
There is a double scrolling bar in my games when I implement the API:
![i80 cimgpsh_orig 1](https://cloud.githubusercontent.com/assets/7591312/11267338/d6436cb6-8ebb-11e5-947d-408274936549.png)
Game link: http://appsworld.gamifive-app.com/html5gameplay/cfd39083c79f294fe7c616026638a8d1/game/island-blocks

I've noticed that double scrollbar is connected to overflow-y being set to scroll in the css file (http://s.motime.com/tbr/less.css?file=app-gameover.less&country=uk-igames&t=20151027150947) If this property is removed, there are no scrollbars. They are not needed anyway as the game resizes to fit the page height. 

Is there anything I should add to my game page or is it possible to remove this line from css file on your side to get rid of this issue?

**Comment by ffognani** [comment]
Hi, the line has been removed from the css file - could you please confirm the issue was solved?

Thank you
