### ISSUE TITLE
Implement storage/retrieve of JSON objects

### ISSUE THREAD

**Issue by enriqueto** [BuongiornoMIP/GamifiveSDK#15]
The level variable isn't enough to represent the current state of the game. Each game should use several of these objects.

For example, my game FootChinko needs to store the ID of the current match, the end result all matches, credits available, power ups purchased, audio state and the last time the player played to compute the daily reward.

**Comment by ffognani** [comment]
Hi, this is a known issue (https://github.com/BuongiornoMIP/GamifiveSDK/wiki/FAQs see #1), we'll let you know as soon as the next version of our SDK with such functionality is ready.

**Comment by enriqueto** [comment]
ok, I'lll wait to the next release
