### ISSUE TITLE
No working load/save data

### ISSUE THREAD

**Issue by alagatar** [BuongiornoMIP/GamifiveSDK#16]
Hi, after try load/save data receive error:
ReferenceError: MOA_API_APPLICATION_OBJECTS_GET is not defined

**Comment by ffognani** [comment]
Hi, this is a bug on our side due to major updates of the SDK and will be fixed as soon as possible. We'll notify you when it's fixed! Thanks for your feedback.

**Comment by alagatar** [comment]
Fixed
