### ISSUE TITLE
GamefiveSDK.Error init has not been called

### ISSUE THREAD

**Issue by blackmoondev** [BuongiornoMIP/GamifiveSDK#18]
Hi there - we have a problem, where SDK ignores the init call and than claim star session can't be called because init hasn't been called. :/

https://dl.dropboxusercontent.com/u/13842529/StartSessionFail.png

**Comment by ffognani** [comment]
Hi, seems like a malformed URL in our API call, we're checking it immediately, thanks for reporting!

**Comment by ffognani** [comment]
Hi, the fix is now online!
