### ISSUE TITLE
testing saveUserData across multiple games

### ISSUE THREAD

**Issue by mentuat** [BuongiornoMIP/GamifiveSDK#19]
I'm using saveUserData and have noticed that the data seems to be shared across all games I am working on.

This is making some games break as they are retrieving data which is not in the format they are expecting.

Is there some way to assign an id for each saveUserData instance (as with localStorage) so this doesn't happen while testing?

**Comment by ffognani** [comment]
Hi, could you give us some more detail about this issue? Are you testing your games in debug mode? Could you provide some links for testing your games?

**Comment by mentuat** [comment]
Hi there, yes the games are in debug mode so I'm assuming the API is using some form of local storage to allow user data to be stored and retrieved while testing?

Would it be possible to generate a unique storage id for each game when in debug mode so games don't overwrite each others data on the same device?

I'm unable to upload examples at the moment but let me know if the above isn't clear and I'll try to upload something at a later time

**Comment by ffognani** [comment]
Hi, the fix is online! I'm closing this issue.
