### ISSUE TITLE
Unknown server error (502) while using gamefive-app

### ISSUE THREAD

**Issue by blackmoondev** [BuongiornoMIP/GamifiveSDK#20]
Hey - for last few days I get 

Unknown server error (502).

when trying to upload new versions of the games with 
http://www.gamifive-app.com/utility/gamifivesdk-support/upload.html

Is there anything wrong with the server?

Cheers
Robert

**Comment by ffognani** [comment]
Hi Robert,

we're investigating on that and we'll let you know as soon as possible.
Thanks for reporting!

**Comment by blackmoondev** [comment]
Hi there. Any news about this issue?
Cheers:)
Robert

**Comment by ffognani** [comment]
Hi, we're still investigating on this :)

Cheers,
Fabio

**Comment by ffognani** [comment]
@blackmoondev could you please tell me the size of the zip you were trying to upload?

**Comment by blackmoondev** [comment]
usually game size - something between 1.5 - 4 megabytes

**Comment by blackmoondev** [comment]
Hey - any updates on this issue?

**Comment by ffognani** [comment]
Hi @blackmoondev could you please tell me which version of Chrome are you using to upload your package? Thanks!

**Comment by blackmoondev** [comment]
It's Version 51.0.2704.103 m Win 8.1

**Comment by ffognani** [comment]
Thank you, we suspect it could be a compatibility issue between the latest Chrome versions and Atlassian's script that connects our form to Jira. Still investigating, we hope to fix this issue soon.

**Comment by blackmoondev** [comment]
Hey - I get the same error on Firefox and IE

**Comment by blackmoondev** [comment]
Hey - any news?

**Comment by MatteoDonniniBuongiorno** [comment]
Hi Robert, we are still investigating (Jira dev are actually). It seems it's a permission issue. Please, submit your game packages via e-mail or downloadable link until it hasn't been fixed. Thanks a lot.

**Comment by MatteoDonniniBuongiorno** [comment]
hi @blackmoondev, this should be fixed. Can you please confirm it? thanks a lot

**Comment by blackmoondev** [comment]
Hey - yes, I confirm it works now:)

**Comment by MatteoDonniniBuongiorno** [comment]
thanks!
